# -*- coding: utf-8 -*-
"""IT25101528_Model_LogisticRegression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11cTIqdAzw28LDfRE-HtSXQuB5_f-jK2h

# Member 1 — LogisticRegression
Hewapathirana S.L. · IT25101528

Created by Kaveesha Tennakoon. The saved test set has been used in earlier versions; use it as a reproducible benchmark, not untouched external validation.

## 01 · Load raw cleaned feature rows and fixed split
"""

from pathlib import Path
import sys, os
# In Colab: upload/extract the COMPLETE corrected project ZIP first.
# If needed set PROJECT_ROOT = Path('/content/MLB-B9G2-06').
PROJECT_ROOT = next((p for base in [Path.cwd(), *Path.cwd().parents, Path('/content')]
                     for p in [base, base/'MLB-B9G2-06']
                     if (p/'src/project_core.py').exists()), None)
if PROJECT_ROOT is None:
    raise FileNotFoundError('Extract the complete project ZIP and set PROJECT_ROOT above.')
sys.path.insert(0, str(PROJECT_ROOT/'src'))
import matplotlib
matplotlib.use('Agg')
from project_core import *
from IPython.display import display
from threadpoolctl import threadpool_limits
thread_limit = threadpool_limits(limits=2)
raw, clean, X_train, X_test, y_train, y_test = load_dataset(PROJECT_ROOT)
print('Raw / clean / train / test:', len(raw), len(clean), len(X_train), len(X_test))

"""## 02 · Inspect the full preprocessing recipe
Every fold fits its own imputation, optional BMI bounds, scaler and encoder. No globally processed matrix enters CV.
"""

import inspect
print(inspect.getsource(RawPreparation))
display(make_preprocessor())

"""## 03 · Define six genuinely different candidates
P1: original features, no capping. P2: BMI capping + derived features. Three parameter settings each. Uniform class weighting preserves empirical prevalence; unlike the old balanced-weight runs, scores are therefore not a controlled preprocessing-only comparison. No threshold tuning.
"""

member=1
model,parameter_grid=model_and_grid(member)
pipeline=Pipeline([("preprocess",make_preprocessor()),("model",model)])
display(pd.DataFrame(parameter_grid))

"""## 04 · Tune with 3-fold stratified cross-validation
Primary selection: mean validation F1. Also record precision, recall, accuracy, ROC-AUC and average precision. Fold SD is variability across folds, not a confidence interval. Six candidates × three folds = 18 CV fits, then one refit on all training rows. MLP early stopping is disabled so an internal validation split cannot inherit pre-fitted preprocessing.
"""

cv=StratifiedKFold(n_splits=3,shuffle=True,random_state=SEED)
search=GridSearchCV(pipeline,parameter_grid,cv=cv,
    scoring={'f1':'f1','precision':'precision','recall':'recall','accuracy':'accuracy','roc_auc':'roc_auc','average_precision':'average_precision'},
    refit='f1',n_jobs=1,return_train_score=True,error_score='raise',verbose=1)
with warnings.catch_warnings(record=True) as observed_warnings:
    warnings.simplefilter('always')
    search.fit(X_train,y_train)
warning_text='\n'.join(sorted(set(str(w.message) for w in observed_warnings)))
(PROJECT_ROOT/f'results/logs/m{member}_warnings.txt').write_text(warning_text or 'No warnings captured.')
print('Best CV F1:',search.best_score_,'Parameters:',search.best_params_)
print(warning_text or 'No warnings captured.')

"""## 05 · Show candidates, test evaluation and fitted pipeline export
Test is used after this notebook has selected its candidate. Group presentation recommendation is selected by CV F1, not test ranking. This module writes CSV/JSON evidence, annotated figures and a raw-input joblib pipeline.
"""

result,candidates=finalize_classifier(PROJECT_ROOT,member,search,X_test,y_test)
display(candidates[["candidate","params","mean_test_f1","std_test_f1","mean_test_recall","mean_test_precision"]])
display(pd.DataFrame([result]))

"""## 06 · Verify raw-input inference after reload
Load only trusted artifacts made by this project. Keep `src/project_core.py` and matching dependency versions alongside the model.
"""

saved=joblib.load(PROJECT_ROOT/f"models/m{member}_{MODELS[member]}_pipeline.joblib")
example=X_test.head(3)
display(example)
print("Predictions:",saved.predict(example))
assert np.array_equal(saved.predict(example),search.best_estimator_.predict(example))